### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TrySound** [natearmagost/zAccordion#5]
Change image tag in html example to img. It's confusing.

And I recommned you to add documention to github README.md file
If you want, I can make PR.

**Comment by natearmagost** [comment]
TrySound,

I'm not sure what you mean by "Change image tag in html example to img." Can you do a pull request or give me a bit more info?

**Comment by TrySound** [comment]
Here http://www.armagost.com/zaccordion/ in html section
